BlogDemo/BlogDemo/Controllers/MessageController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BlogDemo.Controllers
{
    public class MessageController : Controller
    {
        Message2Manager mm = new Message2Manager(new EfMessage2Repository());
        Context c = new Context();
        public IActionResult InBox()
        {
            var username = User.Identity.Name;
            var usermail = c.Users.Where(x => x.UserName == username).Select(y => y.Email).FirstOrDefault();
            var writerID = c.Writers.Where(x => x.WriterMail == usermail).Select(y => y.WirterID).FirstOrDefault();
            var values = mm.GetInboxListByWriter(writerID);
            return View(values);
        }
        public IActionResult SendBox()
        {
            var username = User.Identity.Name;
            var usermail = c.Users.Where(x => x.UserName == username).Select(y => y.Email).FirstOrDefault();
            var writerID = c.Writers.Where(x => x.WriterMail == usermail).Select(y => y.WirterID).FirstOrDefault();
            var values = mm.GetSendboxListByWriter(writerID);
            return View(values);
        }


        [HttpGet]
        public IActionResult MessageDetails(int id)
        {
            var value = mm.TGetById(id);
            return View(value);
        }
        [HttpGet]
        public IActionResult SendMessage()
        {
            return View();
        }
        [HttpPost]
        public IActionResult SendMessage(Message2 p,string ReceiverEmail)
        {
            var username = User.Identity.Name;
            var usermail = c.Users.Where(x => x.UserName == username).Select(y => y.Email).FirstOrDefault();
            var writerID = c.Writers.Where(x => x.WriterMail == usermail).Select(y => y.WirterID).FirstOrDefault();
            var receiverID = c.Writers.Where(x => x.WriterMail == ReceiverEmail).Select(y => y.WirterID).FirstOrDefault();
            p.SenderID = writerID;
            p.ReceiverID = receiverID;
            if (receiverID == 0)
            {
                ModelState.AddModelError("ReceiverEmail", "Alıcı bulunamadı.");
                return View(p);
            }
            p.MessageStatus = true;
            p.MessageDate = Convert.ToDateTime(DateTime.Now.ToShortDateString());
            mm.TAdd(p);
            return RedirectToAction("InBox");
        }
    }
}

BlogDemo/BlogDemo/Views/Message/InBox.cshtml
@using EntityLayer.Concrete
@model List<Message2>

@{
    ViewData["Title"] = "InBox";
    Layout = "~/Views/Shared/WriterLayout.cshtml";
}

<h1>Gelen Kutusu</h1>
<br />
<table class="table table-responsive">
    <tr>
        <th>#</th>
        <th>Konu</th>
        <th>Gönderen</th>
        <th>Tarih</th>
        <th>Mesajı Aç</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <th class="btn-dark">@item.MessageID</th>
            <th>@item.Subject</th>

            <!-- Eğer SenderUser null ise "Bilinmeyen Kullanıcı" yazsın -->
            <th>@(item.SenderUser != null ? item.SenderUser.WriterName : "Bilinmeyen Kullanıcı")</th>

            <td>@(((DateTime)item.MessageDate).ToString("dd-MMM-yyyy"))</td>
            <td><a href="/Message/MessageDetails/@item.MessageID" class="btn btn-warning">Mesajı Aç</a></td>
        </tr>
    }
</table>
<a href="/Message/SendMessage" class="btn btn-danger">Yeni Mesaj Oluştur</a>
<a href="/Message/SendBox" class="btn btn-danger">Gönderilen Mesajlar</a>

BlogDemo/BlogDemo/Views/Message/MessageDetails.cshtml
@model EntityLayer.Concrete.Message2

@{
    ViewData["Title"] = "MessageDetails";
    Layout = "~/Views/Shared/WriterLayout.cshtml";
}

<h1>Mesaj Detay Sayfası</h1>
<br />
@Html.Label("Mesaj ID")
@Html.TextBoxFor(x => x.MessageID, new { @class = "form-control", @disabled = "disabled" })
<br />
@Html.Label("Mesajın Başlığı")
@Html.TextBoxFor(x => x.Subject, new { @class = "form-control", @disabled = "disabled" })
<br />
@Html.Label("Mesajın İçeriği")
@Html.TextAreaFor(x => x.MessageDetails, 10, 3, new { @class = "form-control", @disabled = "disabled" })
<br />
<a class=" btn btn-success" href="/Message/InBox/">Mesajlara Dön</a>

BlogDemo/BlogDemo/Views/Message/SendBox.cshtml
@using EntityLayer.Concrete
@model List<Message2>
@{
    ViewData["Title"] = "SendBox";
    Layout = "~/Views/Shared/WriterLayout.cshtml";
}

<h1>Giden Kutusu</h1>
<br />
<table class="table table-responsive">
    <tr>
        <th>#</th>
        <th>Konu</th>
        <th>Alıcı</th>
        <th>Tarih</th>
        <th>Mesajı Aç</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <th class="btn-dark">@item.MessageID</th>
            <th>@item.Subject</th>
            <th>@item.ReceiverUser.WriterName</th>
            <td>@(((DateTime)item.MessageDate).ToString("dd-MMM-yyyy"))</td>
            <td><a href="/Message/MessageDetails/@item.MessageID" class="btn btn-warning">Mesajı Aç</a></td>
        </tr>
    }
</table>
<a href="/Message/InBox" class="btn btn-primary">Mesajlara Geri Dön</a>

BlogDemo/BlogDemo/Views/Message/SendMessage.cshtml
@model EntityLayer.Concrete.Message2

@{
    ViewData["Title"] = "SendMessage";
    Layout = "~/Views/Shared/WriterLayout.cshtml";
}

<h1>Yeni Mesaj Oluştur</h1>
<br />
@using (Html.BeginForm("SendMessage", "Message", FormMethod.Post))
{
    @Html.Label("Alıcı")
    @* @Html.TextBoxFor(x => x.Subject, new { @class = "form-control" }) *@
    <input type="email" name="ReceiverEmail" id="ReceiverEmail" class="form-control" />
    <br />
    @Html.Label("Konu")
    @Html.TextBoxFor(x => x.Subject, new { @class = "form-control" })
    <br />
    @Html.Label("Mesajınız")
    @Html.TextAreaFor(x => x.MessageDetails, 10, 3, new { @class = "form-control" })
    <br />
    <button class="btn btn-success">Mesajı Gönder</button>
    <a href="/Message/InBox" class="btn btn-danger">İptal</a>
}